### ISSUE TITLE
Error while installing skf in windows

### ISSUE THREAD

**Issue by MKeiner** [blabla1337/skf-flask#101]
I get below error while installing skf in my windows machine. would you be able to help me?
Error message:

```
Traceback (most recent call last):
File "C:\Python27\Lib\site-packages\skf\skf.py", line 23, in <module>
from OpenSSL import SSL, rand
File "C:\Python27\lib\site-packages\OpenSSL__init.py", line 8, in <module>
from OpenSSL import rand, crypto, SSL
File "C:\Python27\lib\site-packages\OpenSSL\rand.py", line 12, in <module>
from OpenSSL._util import (
File "C:\Python27\lib\site-packages\OpenSSL_util.py", line 9, in <module>
binding = Binding()
File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\openssl\bindi
ng.py", line 114, in init__
self._ensure_ffi_initialized()
File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\openssl\bindi
ng.py", line 126, in _ensure_ffi_initialized
cls._modules,
File "C:\Python27\lib\site-packages\cryptography\hazmat\bindings\utils.py", li
ne 31, in load_library_for_binding
lib = ffi.verifier.load_library()
File "C:\Python27\lib\site-packages\cffi\verifier.py", line 114, in load_libra
ry
return self._load_library()
File "C:\Python27\lib\site-packages\cffi\verifier.py", line 225, in _load_libr
ary
return self._vengine.load_library()
File "C:\Python27\lib\site-packages\cffi\vengine_cpy.py", line 174, in load_li
brary
lst = list(map(self.ffi._get_cached_btype, lst))
File "C:\Python27\lib\site-packages\cffi\api.py", line 409, in _get_cached_bty
pe
BType = type.get_cached_btype(self, finishlist)
File "C:\Python27\lib\site-packages\cffi\model.py", line 61, in get_cached_bty
pe
BType = self.build_backend_type(ffi, finishlist)
File "C:\Python27\lib\site-packages\cffi\model.py", line 507, in build_backend
_type
base_btype = self.build_baseinttype(ffi, finishlist)
File "C:\Python27\lib\site-packages\cffi\model.py", line 525, in build_baseint
type
% self._get_c_name())
cffi.api.CDefError: 'point_conversion_form_t' has no values explicitly defined:
refusing to guess which integer type it is meant to be (unsigned/signed, int/lon
g)
```

**Comment by RiieCco** [comment]
Hey,

Would it be optional for you to use a docker container?
We are trying to get away from the manual installation since managing
dependency's is starting
to become a little hard. That is why we build a docker container for easy
deploiment :-)

Cheers!

2016-11-14 10:08 GMT+01:00 MKeiner <notifications@github.com>:

**Comment by blabla1337** [comment]
Solved in new release
