### ISSUE TITLE
ERROR: yum_package[python-pip.noarch] not found during installation

### ISSUE THREAD

**Issue by illnino** [blabla1337/skf-flask#108]
Install using automatic script.

Run 
```
cd ~/
wget https://github.com/blabla1337/owasp-skf-chef/archive/master.zip
unzip master.zip
cd owasp-skf-chef-master
kitchen converge default
```

Got below error.

MacOS: 10.11

-----

`default-centos-71.log`

```
I, [2016-12-20T16:34:18.215749 #93302]  INFO -- default-centos-71: -----> Converging <default-centos-71>...
I, [2016-12-20T16:34:18.216361 #93302]  INFO -- default-centos-71: Preparing files for transfer
I, [2016-12-20T16:34:18.216437 #93302]  INFO -- default-centos-71: Preparing dna.json
I, [2016-12-20T16:34:18.216842 #93302]  INFO -- default-centos-71: Resolving cookbook dependencies with Berkshelf 5.2.0...
I, [2016-12-20T16:34:19.077518 #93302]  INFO -- default-centos-71: Removing non-cookbook files before transfer
I, [2016-12-20T16:34:19.109203 #93302]  INFO -- default-centos-71: Preparing solo.rb
I, [2016-12-20T16:34:19.369273 #93302]  INFO -- default-centos-71: -----> Chef Omnibus installation detected (install only if missing)
I, [2016-12-20T16:34:19.463734 #93302]  INFO -- default-centos-71: Transferring files to <default-centos-71>
I, [2016-12-20T16:34:21.866507 #93302]  INFO -- default-centos-71: Starting Chef Client, version 12.17.44
I, [2016-12-20T16:34:23.672921 #93302]  INFO -- default-centos-71: resolving cookbooks for run list: ["owasp-skf::default"]
I, [2016-12-20T16:34:23.853085 #93302]  INFO -- default-centos-71: Synchronizing Cookbooks:
I, [2016-12-20T16:34:23.872199 #93302]  INFO -- default-centos-71:   - owasp-skf (0.1.2)
I, [2016-12-20T16:34:23.872250 #93302]  INFO -- default-centos-71: Installing Cookbook Gems:
I, [2016-12-20T16:34:23.872266 #93302]  INFO -- default-centos-71: Compiling Cookbooks...
I, [2016-12-20T16:34:23.872280 #93302]  INFO -- default-centos-71: Converging 22 resources
I, [2016-12-20T16:34:23.873448 #93302]  INFO -- default-centos-71: Recipe: owasp-skf::epel
I, [2016-12-20T16:34:29.483230 #93302]  INFO -- default-centos-71:   * yum_package[epel-release] action install (up to date)
I, [2016-12-20T16:34:29.483292 #93302]  INFO -- default-centos-71: Recipe: owasp-skf::skf
I, [2016-12-20T16:34:29.483320 #93302]  INFO -- default-centos-71:   * yum_package[gcc.x86_64] action install (up to date)
I, [2016-12-20T16:34:37.069741 #93302]  INFO -- default-centos-71:   * yum_package[python-pip.noarch] action install
I, [2016-12-20T16:34:37.079483 #93302]  INFO -- default-centos-71:     * No candidate version available for python-pip.noarch
I, [2016-12-20T16:34:37.079536 #93302]  INFO -- default-centos-71:     ================================================================================
I, [2016-12-20T16:34:37.079580 #93302]  INFO -- default-centos-71:     Error executing action `install` on resource 'yum_package[python-pip.noarch]'
I, [2016-12-20T16:34:37.079605 #93302]  INFO -- default-centos-71:     ================================================================================
I, [2016-12-20T16:34:37.079620 #93302]  INFO -- default-centos-71:     
I, [2016-12-20T16:34:37.079633 #93302]  INFO -- default-centos-71:     Chef::Exceptions::Package
I, [2016-12-20T16:34:37.079646 #93302]  INFO -- default-centos-71:     -------------------------
I, [2016-12-20T16:34:37.079659 #93302]  INFO -- default-centos-71:     No candidate version available for python-pip.noarch
I, [2016-12-20T16:34:37.079671 #93302]  INFO -- default-centos-71:     
I, [2016-12-20T16:34:37.079683 #93302]  INFO -- default-centos-71:     Resource Declaration:
I, [2016-12-20T16:34:37.079696 #93302]  INFO -- default-centos-71:     ---------------------
I, [2016-12-20T16:34:37.079709 #93302]  INFO -- default-centos-71:     # In /tmp/kitchen/cache/cookbooks/owasp-skf/recipes/skf.rb
I, [2016-12-20T16:34:37.079721 #93302]  INFO -- default-centos-71:     
I, [2016-12-20T16:34:37.079733 #93302]  INFO -- default-centos-71:      13:   package pkg
I, [2016-12-20T16:34:37.079745 #93302]  INFO -- default-centos-71:      14: end
I, [2016-12-20T16:34:37.079757 #93302]  INFO -- default-centos-71:     
I, [2016-12-20T16:34:37.079769 #93302]  INFO -- default-centos-71:     Compiled Resource:
I, [2016-12-20T16:34:37.079781 #93302]  INFO -- default-centos-71:     ------------------
I, [2016-12-20T16:34:37.079794 #93302]  INFO -- default-centos-71:     # Declared in /tmp/kitchen/cache/cookbooks/owasp-skf/recipes/skf.rb:13:in `block in from_file'
I, [2016-12-20T16:34:37.079816 #93302]  INFO -- default-centos-71:     
I, [2016-12-20T16:34:37.079829 #93302]  INFO -- default-centos-71:     yum_package("python-pip.noarch") do
I, [2016-12-20T16:34:37.079842 #93302]  INFO -- default-centos-71:       package_name "python-pip.noarch"
I, [2016-12-20T16:34:37.079854 #93302]  INFO -- default-centos-71:       action [:install]
I, [2016-12-20T16:34:37.079865 #93302]  INFO -- default-centos-71:       retries 0
I, [2016-12-20T16:34:37.079877 #93302]  INFO -- default-centos-71:       retry_delay 2
I, [2016-12-20T16:34:37.079889 #93302]  INFO -- default-centos-71:       default_guard_interpreter :default
I, [2016-12-20T16:34:37.079900 #93302]  INFO -- default-centos-71:       declared_type :package
I, [2016-12-20T16:34:37.079913 #93302]  INFO -- default-centos-71:       cookbook_name "owasp-skf"
I, [2016-12-20T16:34:37.079924 #93302]  INFO -- default-centos-71:       recipe_name "skf"
I, [2016-12-20T16:34:37.079936 #93302]  INFO -- default-centos-71:       flush_cache {:before=>false, :after=>false}
I, [2016-12-20T16:34:37.080001 #93302]  INFO -- default-centos-71:     end
I, [2016-12-20T16:34:37.080013 #93302]  INFO -- default-centos-71:     
I, [2016-12-20T16:34:37.080024 #93302]  INFO -- default-centos-71:     Platform:
I, [2016-12-20T16:34:37.080037 #93302]  INFO -- default-centos-71:     ---------
I, [2016-12-20T16:34:37.080049 #93302]  INFO -- default-centos-71:     x86_64-linux
I, [2016-12-20T16:34:37.080061 #93302]  INFO -- default-centos-71:     
I, [2016-12-20T16:34:37.080073 #93302]  INFO -- default-centos-71: 
I, [2016-12-20T16:34:37.080084 #93302]  INFO -- default-centos-71: Running handlers:
I, [2016-12-20T16:34:37.082130 #93302]  INFO -- default-centos-71: [2016-12-20T08:34:37+00:00] ERROR: Running exception handlers
I, [2016-12-20T16:34:37.082208 #93302]  INFO -- default-centos-71: Running handlers complete
I, [2016-12-20T16:34:37.082248 #93302]  INFO -- default-centos-71: [2016-12-20T08:34:37+00:00] ERROR: Exception handlers complete
I, [2016-12-20T16:34:37.082273 #93302]  INFO -- default-centos-71: Chef Client failed. 0 resources updated in 15 seconds
I, [2016-12-20T16:34:37.100664 #93302]  INFO -- default-centos-71: [2016-12-20T08:34:37+00:00] FATAL: Stacktrace dumped to /tmp/kitchen/cache/chef-stacktrace.out
I, [2016-12-20T16:34:37.100728 #93302]  INFO -- default-centos-71: [2016-12-20T08:34:37+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
I, [2016-12-20T16:34:37.100751 #93302]  INFO -- default-centos-71: [2016-12-20T08:34:37+00:00] ERROR: yum_package[python-pip.noarch] (owasp-skf::skf line 13) had an error: Chef::Exceptions::Package: No candidate version available for python-pip.noarch
I, [2016-12-20T16:34:37.207544 #93302]  INFO -- default-centos-71: [2016-12-20T08:34:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
E, [2016-12-20T16:34:37.347812 #93302] ERROR -- default-centos-71: Converge failed on instance <default-centos-71>.
E, [2016-12-20T16:34:37.347957 #93302] ERROR -- default-centos-71: ------Exception-------
E, [2016-12-20T16:34:37.347991 #93302] ERROR -- default-centos-71: Class: Kitchen::ActionFailed
E, [2016-12-20T16:34:37.348012 #93302] ERROR -- default-centos-71: Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --no-color --json-attributes /tmp/kitchen/dna.json  --force-formatter
']
E, [2016-12-20T16:34:37.348030 #93302] ERROR -- default-centos-71: ----------------------
E, [2016-12-20T16:34:37.348047 #93302] ERROR -- default-centos-71: ------Backtrace-------
E, [2016-12-20T16:34:37.348062 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/provisioner/base.rb:86:in `rescue in call'
E, [2016-12-20T16:34:37.348079 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/provisioner/base.rb:89:in `call'
E, [2016-12-20T16:34:37.348095 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:380:in `block in converge_action'
E, [2016-12-20T16:34:37.348117 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:520:in `synchronize_or_call'
E, [2016-12-20T16:34:37.348134 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:485:in `block in action'
E, [2016-12-20T16:34:37.348149 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2016-12-20T16:34:37.348164 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:484:in `action'
E, [2016-12-20T16:34:37.348179 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:376:in `converge_action'
E, [2016-12-20T16:34:37.348194 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:355:in `block in transition_to'
E, [2016-12-20T16:34:37.348208 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:354:in `each'
E, [2016-12-20T16:34:37.348223 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:354:in `transition_to'
E, [2016-12-20T16:34:37.348238 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:138:in `converge'
E, [2016-12-20T16:34:37.348254 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:201:in `public_send'
E, [2016-12-20T16:34:37.348268 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:201:in `run_action_in_thread'
E, [2016-12-20T16:34:37.348284 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
E, [2016-12-20T16:34:37.348299 #93302] ERROR -- default-centos-71: ----End Backtrace-----
E, [2016-12-20T16:34:37.348313 #93302] ERROR -- default-centos-71: ---Nested Exception---
E, [2016-12-20T16:34:37.348327 #93302] ERROR -- default-centos-71: Class: Kitchen::Transport::SshFailed
E, [2016-12-20T16:34:37.348344 #93302] ERROR -- default-centos-71: Message: SSH exited (1) for command: [sh -c '
TEST_KITCHEN="1"; export TEST_KITCHEN
sudo -E /opt/chef/bin/chef-solo --config /tmp/kitchen/solo.rb --log_level auto --no-color --json-attributes /tmp/kitchen/dna.json  --force-formatter
']
E, [2016-12-20T16:34:37.348357 #93302] ERROR -- default-centos-71: ----------------------
E, [2016-12-20T16:34:37.348432 #93302] ERROR -- default-centos-71: ------Backtrace-------
E, [2016-12-20T16:34:37.348442 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/provisioner/base.rb:86:in `rescue in call'
E, [2016-12-20T16:34:37.348451 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/provisioner/base.rb:89:in `call'
E, [2016-12-20T16:34:37.348460 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:380:in `block in converge_action'
E, [2016-12-20T16:34:37.348469 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:520:in `synchronize_or_call'
E, [2016-12-20T16:34:37.348477 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:485:in `block in action'
E, [2016-12-20T16:34:37.348486 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/2.3.0/benchmark.rb:293:in `measure'
E, [2016-12-20T16:34:37.348499 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:484:in `action'
E, [2016-12-20T16:34:37.348510 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:376:in `converge_action'
E, [2016-12-20T16:34:37.348524 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:355:in `block in transition_to'
E, [2016-12-20T16:34:37.348533 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:354:in `each'
E, [2016-12-20T16:34:37.348542 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:354:in `transition_to'
E, [2016-12-20T16:34:37.348550 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/instance.rb:138:in `converge'
E, [2016-12-20T16:34:37.348559 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:201:in `public_send'
E, [2016-12-20T16:34:37.348567 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:201:in `run_action_in_thread'
E, [2016-12-20T16:34:37.348576 #93302] ERROR -- default-centos-71: /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/test-kitchen-1.13.2/lib/kitchen/command.rb:173:in `block (2 levels) in run_action'
E, [2016-12-20T16:34:37.348584 #93302] ERROR -- default-centos-71: ----End Backtrace-----
```

**Comment by xandfury** [comment]
Have you tried the Mac OSX manual installation? Given at [https://github.com/blabla1337/skf-flask/blob/master/README.md#mac-osx-manual-installation](url)

**Comment by illnino** [comment]
Thanks.Docker works fine.But I didn't try manual installation for Mac.
Unfortunately,chef didn't work.Hope you could spend some time on it.

Get Outlook for iOS




On Tue, Dec 20, 2016 at 8:35 PM +0800, "Abhinav Saxena" <notifications@github.com> wrote:












Have you tried the Mac OSX manual installation? Given at https://github.com/blabla1337/skf-flask/blob/master/README.md#mac-osx-manual-installation

**Comment by javabeanz** [comment]
I have the same issue with SKF on Centos. There is already a python-pip.noarch version installed too.

**Comment by blabla1337** [comment]
Don't use the python pip package anymore, this is deprecated
