### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by Tikam02** [blabla1337/skf-flask#503]
@blabla1337  Login Error 
![Screenshot from 2019-03-22 01-52-16](https://user-images.githubusercontent.com/10548085/54782842-d61a1a00-4c45-11e9-9422-4aed7930eafa.png)

**Comment by harshant** [comment]
hey,
have you tried with email "example@owasp.org", here is a nice blog https://medium.com/@priyankajain997/installing-security-knowledge-framework-skf-233f08a6c1ff

**Comment by blabla1337** [comment]
Let me know if you succeed, otherwise join our chat channel so I can help you debug it.
https://gitter.im/Security-Knowledge-Framework/Lobby

**Comment by lorentinoooo** [comment]
Hi, I just want to deploy the docker in a remote machine. My command is:

docker run -v /home/ubuntu/development/skf-flask/skf/db/db.sqlite:/skf-flask/skf/db/db.sqlite -e "ORIGIN=ctf.e-paths.com" -e "JWT_SECRET=ANY_SECRET" -p 443:443 blabla1337/skf-flask:stable

but I am unable to activate the admin account. 

I think the problem is my database. I have just created in /home/ubuntu/development/skf-flask/skf/db/ with "sqlite3 db.sqlite" to create the database.

Can anyone help me out, please?

**Comment by lorentinoooo** [comment]
It might be helpful: 
2019-04-03 14:48:31,458 - flask.app - ERROR - Exception on /api/user/login [POST]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib/python3.6/site-packages/flask_restplus/api.py", line 325, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/resource.py", line 44, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/flask_restplus/marshalling.py", line 136, in wrapper
    resp = f(*args, **kwargs)
  File "/skf-flask/skf/api/user/endpoints/user_login.py", line 25, in post
    result = login_user(data)
  File "/skf-flask/skf/api/user/business.py", line 46, in login_user
    if (users.query.filter(users.userName == username).one()):
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3039, in one
    ret = self.one_or_none()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3008, in one_or_none
    ret = list(self)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3081, in __iter__
    return self._execute_and_instances(context)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3103, in _execute_and_instances
    querycontext, self._connection_from_session, close_with_result=True
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3111, in _get_bind_args
    mapper=self._bind_mapper(), clause=querycontext.statement, **kw
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3096, in _connection_from_session
    conn = self.session.connection(**kw)
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1120, in connection
    execution_options=execution_options,
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1126, in _connection_for_bind
    engine, execution_options
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 401, in _connection_for_bind
    self._assert_active()
  File "/usr/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 288, in _assert_active
    % self._rollback_exception
sqlalchemy.exc.InvalidRequestError: This Session's transaction has been rolled back due to a previous exception during flush. To begin a new transaction with this Session, first issue Session.rollback(). Original exception was: (sqlite3.OperationalError) no such table: logs [SQL: 'INSERT INTO logs (date, time, threat, ip, "userID", message, status) VALUES (?, ?, ?, ?, ?, ?, ?)'] [parameters: ('2019-04-03', '14:48', 'HIGH', '127.0.0.1', '0', 'PASS', 'User successfully logedin')] (Background on this error at: http://sqlalche.me/e/e3q8)
2019-04-03 14:48:31,477 - werkzeug - INFO - 127.0.0.1 - - [03/Apr/2019 14:48:31] "POST /api/user/login HTTP/1.1" 500 -

**Comment by blabla1337** [comment]
Hmm looks like something is going wrong with the database file. I also see you use the option to host the DB file outside the Docker. Are you sure it has access and the paths are correct? But it does look like that is where the problem is.

You could verify by starting it without the volume part and removing this:
-v /home/ubuntu/development/skf-flask/skf/db/db.sqlite:/skf-flask/skf/db/db.sqlite
