### ISSUE TITLE
Bare metal installation fails

### ISSUE THREAD

**Issue by samadhi1978** [blabla1337/skf-flask#734]
Hi, I am trying to install SKF past two days on clean Ubuntu 20.04. I have updated it to the latest version and started go follow the steps in the installation process. My observation is that pip3 installation is missing so you need add the additional step after:
cd /tmp; git clone git://github.com/blabla1337/skf-flask.git 
such as:
sudo apt install python3-pip
then when run next: /tmp# cd /tmp/skf-flask; sudo pip3 install -r requirements.txt
It fails and I get following:

  **ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-azy2cwvy/rake-nltk/setup.py'"'"'; __file__='"'"'/tmp/pip-install-azy2cwvy/rake-nltk/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-fdj9m66c
       cwd: /tmp/pip-install-azy2cwvy/rake-nltk/
  Complete output (57 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  creating build/lib/rake_nltk
  copying rake_nltk/__init__.py -> build/lib/rake_nltk
  copying rake_nltk/__version__.py -> build/lib/rake_nltk
  copying rake_nltk/rake.py -> build/lib/rake_nltk
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/rake_nltk
  copying build/lib/rake_nltk/__init__.py -> build/bdist.linux-x86_64/wheel/rake_nltk
  copying build/lib/rake_nltk/__version__.py -> build/bdist.linux-x86_64/wheel/rake_nltk
  copying build/lib/rake_nltk/rake.py -> build/bdist.linux-x86_64/wheel/rake_nltk
  running install_egg_info
  running egg_info
  writing rake_nltk.egg-info/PKG-INFO
  writing dependency_links to rake_nltk.egg-info/dependency_links.txt
  writing requirements to rake_nltk.egg-info/requires.txt
  writing top-level names to rake_nltk.egg-info/top_level.txt
  reading manifest file 'rake_nltk.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  writing manifest file 'rake_nltk.egg-info/SOURCES.txt'
  Copying rake_nltk.egg-info to build/bdist.linux-x86_64/wheel/rake_nltk-1.0.4.egg-info
  running install_scripts
  Running post installation tasks
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-azy2cwvy/rake-nltk/setup.py", line 44, in <module>
      setup(
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 259, in run
      self.run_command('install')
    File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-install-azy2cwvy/rake-nltk/setup.py", line 36, in run
      self.execute(_post_install, [], msg="Running post installation tasks")
    File "/usr/lib/python3.8/distutils/cmd.py", line 335, in execute
      util.execute(func, args, msg, dry_run=self.dry_run)
    File "/usr/lib/python3.8/distutils/util.py", line 303, in execute
      func(*args)
    File "/tmp/pip-install-azy2cwvy/rake-nltk/setup.py", line 17, in _post_install
      import nltk
  ModuleNotFoundError: No module named 'nltk'
  ----------------------------------------
  ERROR: Failed building wheel for rake-nltk**

**Comment by samadhi1978** [comment]
Well, I can't say it fails because I am able to continue and eventually it gives my working interface but any activation of admin account doesn't seems to happen. Unable to log on because admin account can't be activated.

**Comment by samadhi1978** [comment]
Server address: https://62.31.146.84:2020/auth/login 
ignore SSL certificate error (will get this sorted later). This is fresh installation and whatever you do you can't login.

**Comment by samadhi1978** [comment]
is it dead?

**Comment by samadhi1978** [comment]
is

**Comment by blabla1337** [comment]
we recommend to go for the K8s installation of SKF or using the docker-compose way.
