### ISSUE TITLE
SKF Flask Api docker not working 

### ISSUE THREAD

**Issue by Vigneshkna** [blabla1337/skf-flask#826]
Docker Desktop -> 4.19.0
Docker Image -> blabla1337/skf-api:4.1.1

I'm facing issue in **pika.exceptions.AMQPConnectionError**
BlockingConnection in pika packages, due to this i couldnt establish the connection to the database to frontend, and in localhost i'm getting "The Requested URL notFound" error.

**Terminal stackTrace Log:**
![image](https://user-images.githubusercontent.com/35601923/235667924-82dc880d-2c6b-4438-b700-4c638a6062fe.png)
![image](https://user-images.githubusercontent.com/35601923/235668028-0001e583-0dee-4fe4-a9e5-07b9de5ec54b.png)
![image](https://user-images.githubusercontent.com/35601923/235668164-5d683f55-b559-42c3-89b5-c646df2d9343.png)

**Environment:**
![image](https://user-images.githubusercontent.com/35601923/235668367-2c4adf0e-9203-41da-9bb5-636dffd52910.png)
![image](https://user-images.githubusercontent.com/35601923/235668431-20d6dfdd-8539-4c2e-9259-8907f24c83af.png)

**LocalHost:**
![image](https://user-images.githubusercontent.com/35601923/235668714-7d2adabb-803a-4a5f-b572-46e59558c0bd.png)

**Comment by cptfixit** [comment]
I'm having similar problems. The logging is:

```
skf-api_container | Traceback (most recent call last):
skf-api_container |   File "skf/rabbit_mq_workers/deployment-worker.py", line 207, in <module>
skf-api_container |     channel.start_consuming()
skf-api_container |   File "/home/user_api/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
skf-api_container |     self._process_data_events(time_limit=None)
skf-api_container |   File "/home/user_api/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
skf-api_container |     self.connection.process_data_events(time_limit=time_limit)
skf-api_container |   File "/home/user_api/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
skf-api_container |     self._flush_output(common_terminator)
skf-api_container |   File "/home/user_api/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 522, in _flush_output
skf-api_container |     raise self._closed_result.value.error
skf-api_container | pika.exceptions.StreamLostError: Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')
skf-api_container | Traceback (most recent call last):
skf-api_container |   File "skf/rabbit_mq_workers/deletion-worker.py", line 51, in <module>
skf-api_container |     channel.start_consuming()
skf-api_container |   File "/home/user_api/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 1866, in start_consuming
skf-api_container |     self._process_data_events(time_limit=None)
skf-api_container |   File "/home/user_api/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 2027, in _process_data_events
skf-api_container |     self.connection.process_data_events(time_limit=time_limit)
skf-api_container |   File "/home/user_api/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 825, in process_data_events
skf-api_container |     self._flush_output(common_terminator)
skf-api_container |   File "/home/user_api/.local/lib/python3.7/site-packages/pika/adapters/blocking_connection.py", line 522, in _flush_output
skf-api_container |     raise self._closed_result.value.error
skf-api_container | pika.exceptions.StreamLostError: Stream connection lost: ConnectionResetError(104, 'Connection reset by peer')
```

Interestingly I notice that the RabbitMQ container will automatically die within a few minutes after startup. The logs show:

`skf-rabbitmq_container exited with code 0`

... without a clear indication as to why this would be happening.
